[tool.poetry]
authors = ["Joel Krim <drawjk705@gmail.com>"]
description = ""
name = "us-libraries"
version = "0.1.0"

[tool.poetry.dependencies]
"pdfminer.six" = "^20201018"
beautifulsoup4 = "^4.9.3"
pandas = "^1.2.1"
punq = "^0.4.1"
python = "^3.9"
requests = "^2.25.1"
tabula-py = "^2.2.0"

[tool.poetry.dev-dependencies]
black = { version = "^20.8b1", allow-prereleases = true }
callee = "^0.3.1"
data-science-types = "^0.2.22"
hypothesis = "^6.0.3"
ipython = "^7.19.0"
ipywidgets = "^7.6.2"
isort = "^5.7.0"
jedi = "0.17.2"
jupyter_nbextensions_configurator = "^0.4.1"
jupyterlab = "^3.0.1"
poethepoet = "^0.9.0"
pre-commit = "^2.9.3"
pytest = "^6.2.1"
pytest-clarity = "^0.3.0-alpha.0"
pytest-cov = "^2.11.1"
pytest-mock = "^3.5.0"
pytest-randomly = "^3.5.0"
pytest-sugar = "^0.9.4"
pytest-tldr = "^0.2.2"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
