"""
This type stub file was generated by pyright.
"""

def load_template(path_or_buffer):
    """Build tabula-py option from template file

    Args:
        path_or_buffer (str, path object or file-like object):
            File like object of Tabula app template.

    Returns:
        dict: tabula-py options
    """
    ...

