"""
This type stub file was generated by pyright.
"""

"""
Utility module providing some convenient functions.
"""
def java_version():
    """Show Java version

    Returns:
        str: Result of ``java -version``
    """
    ...

def environment_info():
    """Show environment information for reporting.

    Returns:
        str:
            Detailed information like Python version, Java version,
            or OS environment, etc.
    """
    ...

