"""
This type stub file was generated by pyright.
"""

from pandas.errors import ParserError

class CSVParseError(ParserError):
    """Error represents CSV parse error, which mainly caused by pandas."""
    def __init__(self, message, cause) -> None:
        ...
    


class JavaNotFoundError(Exception):
    """Error represents Java doesn't exist."""
    ...


