"""
This type stub file was generated by pyright.
"""

from .. import Matcher

class be_above_or_equal(Matcher):
    def __init__(self, expected) -> None:
        ...
    


class above_or_equal(be_above_or_equal):
    ...


