"""
This type stub file was generated by pyright.
"""

from .. import Matcher

class contain(Matcher):
    _NON_NORMALIZED_SEQUENCE_TYPES = ...
    def __init__(self, *expected) -> None:
        ...
    
    def __repr__(self):
        ...
    


class contain_exactly(contain):
    ...


class contain_only(contain):
    ...


