"""
This type stub file was generated by pyright.
"""

from .. import Matcher

class _DictMatcher(Matcher):
    def __repr__(self):
        ...
    


class have_keys(_DictMatcher):
    def __init__(self, *args, **kwargs) -> None:
        ...
    


class have_key(_DictMatcher):
    def __init__(self, name, *args) -> None:
        ...
    


