"""
This type stub file was generated by pyright.
"""

from .. import Matcher

class _PropertyMatcher(Matcher):
    def __repr__(self):
        ...
    


class have_properties(_PropertyMatcher):
    def __init__(self, *args, **kwargs) -> None:
        ...
    


class have_property(_PropertyMatcher):
    def __init__(self, name, *args) -> None:
        ...
    


