"""
This type stub file was generated by pyright.
"""

from .. import Matcher

class have_length(Matcher):
    def __init__(self, expected) -> None:
        ...
    


class have_len(have_length):
    ...


