"""
This type stub file was generated by pyright.
"""

from .. import Matcher

class _raise_error(Matcher):
    def __init__(self, expected, *args) -> None:
        ...
    
    def __call__(self, *args, **kwargs):
        ...
    


raise_error = _raise_error(Exception)
