"""
This type stub file was generated by pyright.
"""

from .. import Matcher

class _StarEndWith(Matcher):
    def __init__(self, *args) -> None:
        ...
    
    def __repr__(self):
        ...
    


class start_with(_StarEndWith):
    ...


class end_with(_StarEndWith):
    ...


