"""
This type stub file was generated by pyright.
"""

import sys

"""Python 3 and 2 compatibility support module."""
IS_PY2 = sys.version_info[0] == 2
if IS_PY2:
    string_types = (str, unicode)
else:
    string_types = (bytes, str)
