name: Release
on:
    workflow_dispatch:
        inputs:
            tag:
                description: The tag to release
                required: true
            is_prerelease:
                description: Whether or not this is a prerelease
                required: false
                default: 'false'

jobs:
    pypi-release:
        environment: Release
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v2
              with:
                  ref: refs/tags/${{ github.event.inputs.tag }}

            - name: set up python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9

            - name: install poetry
              uses: snok/install-poetry@v1.1.1
              with:
                  version: 1.1.4
                  virtualenvs-create: true
                  virtualenvs-in-project: true

            - name: load cached venv
              id: cached-poetry-dependencies
              uses: actions/cache@v2
              with:
                  path: .venv
                  key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}-${{ secrets.CACHE_VERSION }}

            - name: install poetry dependencies
              run: poetry install
              if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'

            - name: poetry publish to pypi
              run: |
                  poetry build
                  poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
                  poetry publish

            - name: create release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.event.inputs.tag }}
                  release_name: Release ${{ github.event.inputs.tag }}
                  draft: false
                  prerelease: ${{ github.event.inputs.is_prerelease == 'true' }}
