"""
This type stub file was generated by pyright.
"""

""" Python implementation of Arcfour encryption algorithm.
See https://en.wikipedia.org/wiki/RC4
This code is in the public domain.

"""

class Arcfour:
    def __init__(self, key) -> None: ...
    def process(self, data): ...
    encrypt = ...
