"""
This type stub file was generated by pyright.
"""

def get_bytes(data):
    ...

class BitParser:
    def __init__(self) -> None:
        ...
    
    @classmethod
    def add(cls, root, v, bits):
        ...
    
    def feedbytes(self, data):
        ...
    


class CCITTG4Parser(BitParser):
    MODE = ...
    WHITE = ...
    BLACK = ...
    UNCOMPRESSED = ...
    class EOFB(Exception):
        ...
    
    
    class InvalidData(Exception):
        ...
    
    
    class ByteSkip(Exception):
        ...
    
    
    def __init__(self, width, bytealign=...) -> None:
        ...
    
    def feedbytes(self, data):
        ...
    
    def reset(self):
        ...
    
    def output_line(self, y, bits):
        ...
    


class CCITTFaxDecoder(CCITTG4Parser):
    def __init__(self, width, bytealign=..., reversed=...) -> None:
        ...
    
    def close(self):
        ...
    
    def output_line(self, y, bits):
        ...
    


def ccittfaxdecode(data, params):
    ...

def main(argv):
    class Parser(CCITTG4Parser):
        ...
    
    

if __name__ == '__main__':
    ...
