"""
This type stub file was generated by pyright.
"""

import logging

from .psparser import LIT

log = logging.getLogger(__name__)
LITERAL_PAGE = LIT("Page")
LITERAL_PAGES = LIT("Pages")

class PDFPage:
    """An object that holds the information about a page.

    A PDFPage object is merely a convenience class that has a set
    of keys and values, which describe the properties of a page
    and point to its contents.

    Attributes:
      doc: a PDFDocument object.
      pageid: any Python object that can uniquely identify the page.
      attrs: a dictionary of page attributes.
      contents: a list of PDFStream objects that represents the page content.
      lastmod: the last modified time of the page.
      resources: a list of resources used by the page.
      mediabox: the physical size of the page.
      cropbox: the crop rectangle of the page.
      rotate: the page rotation (in degree).
      annots: the page annotations.
      beads: a chain that represents natural reading order.
    """

    def __init__(self, doc, pageid, attrs) -> None:
        """Initialize a page object.

        doc: a PDFDocument object.
        pageid: any Python object that can uniquely identify the page.
        attrs: a dictionary of page attributes.
        """
        ...
    def __repr__(self): ...
    INHERITABLE_ATTRS = ...
    @classmethod
    def create_pages(cls, document): ...
    @classmethod
    def get_pages(
        cls,
        fp,
        pagenos=...,
        maxpages=...,
        password=...,
        caching=...,
        check_extractable=...,
    ): ...
